### ISSUE TITLE
Error in synchronization of orders

### ISSUE THREAD

**Issue by franzlst** [plentymarkets/plentymarkets-shopware-connector#111]
```
[2017-04-02 20:20:13] plentyconnector.DEBUG: Command received: HandleOrderCommand {"adapterName":"ShopwareAdapter","transferObject":"47e0a984-db0b-46e3-8097-39c3216e1f50"}
[2017-04-02 20:20:13] plentyconnector.ERROR: Command failed: HandleOrderCommand {"adapterName":"ShopwareAdapter","transferObject":"47e0a984-db0b-46e3-8097-39c3216e1f50","exception":"[object] (PlentyConnector\\Connector\\ValidatorService\\Exception\\InvalidDataException(code: 0): PlentyConnector\\Connector\\TransferObject\\Order\\Order ObjectIdentifier: 47e0a984-db0b-46e3-8097-39c3216e1f50 Value \"1\" is not a float. Path: orderItem.quantity at /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/ValidatorService/Exception/InvalidDataException.php:45)"}
[2017-04-02 20:20:13] plentyconnector.ERROR: PlentyConnector\Connector\TransferObject\Order\Order ObjectIdentifier: 47e0a984-db0b-46e3-8097-39c3216e1f50 Value "1" is not a float. Path: orderItem.quantity
[2017-04-02 20:20:13] plentyconnector.ERROR: #0 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/ValidatorService/ValidatorService.php(74): PlentyConnector\Connector\ValidatorService\Exception\InvalidDataException::fromObject(Object(PlentyConnector\Connector\TransferObject\Order\OrderItem\OrderItem), 'Value "1" is no...', 'orderItem.quant...', Array) #1 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/ValidatorService/ValidatorService.php(63): PlentyConnector\Connector\ValidatorService\ValidatorService->validate(Object(PlentyConnector\Connector\TransferObject\Order\OrderItem\OrderItem), Array) #2 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/ServiceBus/ValidatorMiddleware/ValidatorMiddleware.php(43): PlentyConnector\Connector\ValidatorService\ValidatorService->validate(Object(PlentyConnector\Connector\TransferObject\Order\Order)) #3 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/vendor/league/tactician/src/CommandBus.php(62): PlentyConnector\Connector\ServiceBus\ValidatorMiddleware\ValidatorMiddleware->execute(Object(PlentyConnector\Connector\ServiceBus\Command\Order\HandleOrderCommand), Object(Closure)) #4 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/vendor/league/tactician-logger/src/LoggerMiddleware.php(43): League\Tactician\CommandBus->League\Tactician\{closure}(Object(PlentyConnector\Connector\ServiceBus\Command\Order\HandleOrderCommand)) #5 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/vendor/league/tactician/src/CommandBus.php(62): League\Tactician\Logger\LoggerMiddleware->execute(Object(PlentyConnector\Connector\ServiceBus\Command\Order\HandleOrderCommand), Object(Closure)) #6 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/vendor/league/tactician/src/CommandBus.php(42): League\Tactician\CommandBus->League\Tactician\{closure}(Object(PlentyConnector\Connector\ServiceBus\Command\Order\HandleOrderCommand)) #7 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/Connector.php(176): League\Tactician\CommandBus->handle(Object(PlentyConnector\Connector\ServiceBus\Command\Order\HandleOrderCommand)) #8 [internal function]: PlentyConnector\Connector\Connector->PlentyConnector\Connector\{closure}(Object(PlentyConnector\Connector\TransferObject\Order\Order), '47e0a984-db0b-4...') #9 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/Connector.php(179): array_walk(Array, Object(Closure)) #10 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/Connector.php(106): PlentyConnector\Connector\Connector->handleDefinition(Object(PlentyConnector\Connector\ValueObject\Definition\Definition), 'changed', NULL) #11 [internal function]: PlentyConnector\Connector\Connector->PlentyConnector\Connector\{closure}(Object(PlentyConnector\Connector\ValueObject\Definition\Definition), 5) #12 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Connector/Connector.php(107): array_walk(Array, Object(Closure)) #13 /var/www/web1/htdocs/shopware/custom/plugins/PlentyConnector/Console/Command/ProcessCommand.php(99): PlentyConnector\Connector\Connector->handle('changed', 'Order', NULL) #14 /var/www/web1/htdocs/shopware/vendor/symfony/console/Command/Command.php(264): PlentyConnector\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/web1/htdocs/shopware/vendor/symfony/console/Application.php(846): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/web1/htdocs/shopware/engine/Shopware/Components/Console/Application.php(140): Symfony\Component\Console\Application->doRunCommand(Object(PlentyConnector\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/web1/htdocs/shopware/vendor/symfony/console/Application.php(191): Shopware\Components\Console\Application->doRunCommand(Object(PlentyConnector\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /var/www/web1/htdocs/shopware/engine/Shopware/Components/Console/Application.php(132): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /var/www/web1/htdocs/shopware/vendor/symfony/console/Application.php(122): Shopware\Components\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 /var/www/web1/htdocs/shopware/bin/console(38): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #21 {main}

```

**Comment by jochenmanz** [comment]
Thanks for your bug report. I've fixed it for my development branch. The order import part is still WIP, handle with caution.
